################################################################################
# > Playbook used to deploy the SPA on a webserver
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- name: Deploy the SPA on a WebSever
  hosts: spa
  become: yes

  roles:
    - role: spa
      tags: ['spa']
