################################################################################
# > Playbook used to setup a webserver serving the SPA
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- name: Pre-step
  hosts: web
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install Python 2
      raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
      register: __python2_requirement
      changed_when: __python2_requirement.stdout != ""
      tags:
        - always

- name: Configure the WebSever to run the SPA
  hosts: web
  become: yes

  roles:
    - role: Lowess.common
      tags: ['common']

    - role: Lowess.netdata
      tags: ['netdata']

    - role: Lowess.ngrok
      tags: ['ngrok']

    - role: Lowess.nginx
      tags: ['nginx']

- include: deploy.yml

