################################################################################
# > Playbook used to setup a webserver serving the SPA
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- name: Configure the WebSever to run the SPA
  hosts: web
  become: yes

  roles:
    - role: Lowess.common
      tags: ['common']

    - role: Lowess.netdata
      tags: ['netdata']

    - role: Lowess.ngrok
      tags: ['ngrok']

    - role: Lowess.nginx
      tags: ['nginx']

- include: deploy.yml

