################################################################################
# > Playbook used to setup a webserver serving the SPA
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---
- include: python.yml

- name: Configure the WebSever to run the SPA
  hosts: spa
  become: yes

  roles:
    - role: Lowess.common
      tags: ['common']

    - role: Lowess.ngrok
      tags: ['ngrok']

    - role: Lowess.nginx
      tags: ['nginx']

- include: deploy.yml

